### ISSUE TITLE
 Problem with low range

### ISSUE THREAD

**Issue by JairoMsj** [EmenstaNougat/ESP32-BlueJammer#13]
I correctly followed the hardware acquisition. I carried out the assembly without the battery, but as per the instructions. I installed the firmware, as instructed, but the Bluetooth blocking range did not exceed 4 meters. What could have gone wrong?

**Comment by EmenstaNougat** [comment]
It has to be the wiring, several people on the Discord made it recently and it's working. Wiring or hardware
