### ISSUE TITLE
Short range

### ISSUE THREAD

**Issue by pikachu2010** [EmenstaNougat/ESP32-BlueJammer#17]
Hi guys

I have made this bluetooth jammer but the range is only 1 or 2 meters.
What is the problem here?
I use the antennas that came use the module and i have also high gain antennas but is still a few meter 2 or 3.

**Comment by biscuitaep** [comment]
Are you using LNA+PA module?
And which esp32

**Comment by EmenstaNougat** [comment]
It has to be the wiring, poeple have fixed such issues by resoldering, and they've had a shortened pin. Averagre range should be 30m
