### ISSUE TITLE
30 pin

### ISSUE THREAD

**Issue by Lgndwilloske** [EmenstaNougat/ESP32-BlueJammer#6]
Will a 30 pin esp work??

**Comment by EmenstaNougat** [comment]
Hardware
Required:
ESP32 Dev Module (such as ESP32-WROOM-32U, any ESP32 should work as long as it has the needed pins!)
nRF24L01+PA+LNA (2x)
10uF Capacitor (2x) (any voltage above 5V)
Additional:
3rd Antenna: IPEX to SMA-F pigtail
Status LED: 3mm LED
4.7k Ohm Resistor
If you're looking to add a battery:
3.7V Li-Ion Battery
JST PH 2.0 Connector
TP4056 Charging Module (Micro-USB/Type-C)
Mini Slide Switch

**Comment by Lgndwilloske** [comment]
so im guessing its a no then
